version: '3.7'
services:
  kong-db:
    image: postgres:9.6-alpine
    container_name: kong-db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U kong' ]
      interval: 5s
      timeout: 2s
      retries: 15
    networks:
      - proxy-network

  kong-migration:
    image: 'kong:${TAG-latest}'
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    env_file:
      - .env
    restart: on-failure
    networks:
      - proxy-network

  konga-migration:
    image: pantsel/konga
    command: '-c prepare -a postgres -u postgresql://kong:kong@kong-db:5432/konga_db'
    restart: on-failure
    depends_on:
      - kong-db
    networks:
      - proxy-network

  kong:
    image: 'kong:${TAG-latest}'
    container_name: kong
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8444:8444
      - 80:8000
      - 443:8443
    healthcheck:
      test: [ 'CMD', 'kong', 'health' ]
      interval: 5s
      timeout: 2s
      retries: 15
    networks:
      - proxy-network

  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    env_file:
      - .env
    ports:
      - 1337:1337
    networks:
      - proxy-network

networks:
  proxy-network:
